language: csharp
mono: none
dotnet: 2.1.403
script:
  - export kd_module=$(cat .metadata/module | tr -d '\r\n\t ')
  - export kd_project=$(cat .metadata/project | tr -d '\r\n\t ')
  - export kd_version_major=$(cat .metadata/version_major | tr -d '\r\n\t ')
  - export kd_version_minor=$(cat .metadata/version_minor | tr -d '\r\n\t ')
  - export kd_version_patch=$(cat .metadata/version_patch | tr -d '\r\n\t ')
  - export kd_version_build=$TRAVIS_BUILD_NUMBER
  - export kd_version_suffix=-alpha.$kd_version_build
  - echo --------------------------------------------------------------------------------
  - echo "Building $kd_project version $kd_version_major.$kd_version_minor.$kd_version_patch.$kd_version_build"
  - echo --------------------------------------------------------------------------------
  - bash ./do/generatemetadata
  - dotnet build $kd_module/$kd_module.csproj
  - dotnet build $kd_module.Specifications/$kd_module.Specifications.csproj
  - dotnet test $kd_module.Specifications/$kd_module.Specifications.csproj
