language: csharp
mono: none
dotnet: 2.1.403
script:
  - export kd_module=$(cat .metadata/module | xargs)
  - export kd_project=$(cat .metadata/project | xargs)
  - export kd_version_major=$(cat .metadata/version_major | xargs)
  - export kd_version_minor=$(cat .metadata/version_minor | xargs)
  - export kd_version_patch=$(cat .metadata/version_patch | xargs)
  - export kd_version_build=$(cat .metadata/version_build | xargs)
  - export kd_version_suffix=-alpha.$kd_version_build
  - echo "Building $kd_project version $kd_version_major.$kd_version_minor.$kd_version_patch.$kd_version_build"
  - bash ./do/generatemetadata
  - dotnet build $kd_module/$kd_module.csproj
  - dotnet build $kd_module.Specifications/$kd_module.Specifications.csproj
  - dotnet test $kd_module.Specifications/$kd_module.Specifications.csproj
